# AUTO-SYNCED FROM ai-agents/shared/mcp/static.py — DO NOT EDIT THIS FILE DIRECTLY.
# Edit the source in the ai-agents monorepo, then run:
#   python scripts/sync-shared-to-submodules.py
# from the monorepo root. The drift check (--check) runs in CI and will
# fail if this file is out of sync with its source.
"""SPA static file serving with cache control + client-side route fallback.

index.html: never cached (always revalidate after rebuild).
/assets/*: content-hashed filenames, cached forever.

SPA-fallback: 404s on document-shaped paths fall back to `index.html` so
client-side routes (`/workers/iris-qa-tm`, `/?repo=foo&branch=main` etc.)
reload cleanly instead of returning the default 404 body.

OAuth-safe: paths under `.well-known/` and `oauth/` are explicitly
excluded from the SPA fallback. RFC 8414 OAuth 2.0 Authorization Server
Metadata discovery clients parse those responses as JSON and fail with
"SDK auth failed: Failed to parse JSON" if they receive `index.html`
instead of a real 404. Claude Code's `/mcp` Authenticate fetches
`.well-known/oauth-authorization-server` during its auth handshake —
without this guard, the no-extension heuristic in the SPA fallback
would catch it and break authenticate.

Tubemail's `src/tubemail_hub/server.py:_SPAStaticFiles` is an
intentional standalone-distribution mirror of this helper (its container
does not pip-install shared/ — see ai-agents/jjstack/20260428-mcp-server-categories.md
on tubemail being repo_agnostic). Keep behavior between the two copies
in sync when changes are made.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from fastapi import FastAPI


def mount_spa(
    app: FastAPI,
    static_dir: str = "/app/static",
    *,
    no_spa_fallback_prefixes: tuple[str, ...] = (".well-known/", "oauth/"),
) -> None:
    """Mount a React SPA with proper cache headers and client-side route fallback.

    - index.html and .html files: no-cache (always fresh after deploy)
    - /assets/* (Vite hashed bundles): immutable, cached 1 year
    - All other static files: default caching
    - 404 on a document-shaped path → serve index.html (so client-side
      routes like `/workers/iris-qa-tm` reload cleanly)
    - 404 on `.well-known/` or `oauth/` → real 404 (OAuth 2.0 RFC 8414
      discovery clients parse these as JSON; serving index.html breaks
      authenticate handshakes — see Claude Code's `/mcp` auth flow)

    Args:
        app: FastAPI application to mount static files on.
        static_dir: Directory containing the built SPA (default `/app/static`).
        no_spa_fallback_prefixes: Path prefixes that bypass the SPA fallback
            and must always return real 404s. Defaults cover OAuth 2.0
            discovery endpoints. Pass a longer tuple to extend (e.g. add
            `("api/", )` if you want a sub-tree to never serve HTML).
    """
    static_path = Path(static_dir)
    if not static_path.is_dir():
        return

    from starlette.middleware.base import BaseHTTPMiddleware
    from starlette.staticfiles import StaticFiles
    from starlette.exceptions import HTTPException as StarletteHTTPException
    from fastapi import Request

    class _NoCacheIndexMiddleware(BaseHTTPMiddleware):
        async def dispatch(self, request: Request, call_next):
            response = await call_next(request)
            path = request.url.path
            if path == "/" or path.endswith(".html"):
                response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
            elif "/assets/" in path:
                response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
            return response

    class _SPAStaticFiles(StaticFiles):
        """StaticFiles variant that serves `index.html` for any 404 on a
        document-shaped request, so client-side routes reload cleanly.

        Excludes `no_spa_fallback_prefixes` to preserve real 404s for
        contracted-endpoint namespaces (OAuth 2.0 discovery, etc.).
        """

        async def get_response(self, path: str, scope):
            try:
                return await super().get_response(path, scope)
            except StarletteHTTPException as e:
                if e.status_code != 404:
                    raise
                # Excluded prefixes must surface as real 404s.
                if any(path.startswith(p) for p in no_spa_fallback_prefixes):
                    raise
                # Only fall back for document requests, never for an asset
                # (e.g. `/assets/foo.js`) that actually is missing.
                accept = ""
                for k, v in scope.get("headers", []):
                    if k == b"accept":
                        accept = v.decode("latin-1", "ignore")
                        break
                looks_like_doc = (
                    "text/html" in accept
                    or "." not in path.rsplit("/", 1)[-1]
                )
                if not looks_like_doc:
                    raise
                return await super().get_response("index.html", scope)

    app.add_middleware(_NoCacheIndexMiddleware)
    app.mount(
        "/",
        _SPAStaticFiles(directory=str(static_path), html=True),
        name="static",
    )
